name: "PHPStan on Pull Requests"

on:
  pull_request:
    branches:
      - master

jobs:
  unit-tests-on-each-php-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: pcntl

    - name: Composer install
      run: (rm composer.lock || true) &&  composer update

    - name: PHP version
      run: php --version

    - name: PHPStan
      run: vendor/bin/phpstan analyse -l max ./src ./tests