name: CI

on: [push]

jobs:
  build-test:
    inputs:
      - php-version: '7.4'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5
    - uses: php-actions/phpunit@v3
