name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.4'

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5
    - uses: php-actions/phpunit@v3
